# Generated by Django 4.1.3 on 2022-11-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djamsesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
