# Generated by Django 4.1.3 on 2022-11-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djamsesh', '0002_song_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=200)),
                ('imageURL', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
    ]
