# Generated by Django 4.1.3 on 2022-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djamsesh', '0003_artist_remove_song_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('coverURL', models.CharField(max_length=250)),
            ],
        ),
    ]
