# Generated by Django 4.1.3 on 2022-11-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djamsesh', '0006_playlist_song_times_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='djamsesh.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='djamsesh.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='song_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='djamsesh.song'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='djamsesh.genre'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='djamsesh.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='djamsesh.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='djamsesh.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='djamsesh.genre'),
        ),
    ]
