# Generated by Django 4.1.3 on 2022-11-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djamsesh', '0007_album_artist_id_album_genre_id_album_song_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='times_played',
        ),
    ]
